version: '3.8'

services:
  api:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    container_name: leaklens-api
    ports:
      - "10000:3000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - RUST_LOG=info
      - CORS_ALLOWED_ORIGINS=http://localhost:3001,https://${WEBAPP_SERVICE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: leaklens-webapp
    depends_on:
      - api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3000
    restart: unless-stopped 