version: '3.8'

services:
  leaklens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaklens
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - RUST_LOG=info
    volumes:
      - leaklens_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  leaklens_data:
    driver: local 