version: '3.8'

services:
  leaklens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaklens
    ports:
      - "8080:80"
    environment:
      # Server Configuration
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - RUST_LOG=info
      - CORS_ALLOWED_ORIGINS=http://localhost:80,http://localhost:8080

      # Google API Configuration
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_API_URL=https://passwordsleakcheck-pa.googleapis.com/v1/leaks:lookupSingle
      - GOOGLE_TOKEN_URL=https://www.googleapis.com/oauth2/v4/token
      - GOOGLE_API_SCOPE=https://www.googleapis.com/auth/identity.passwords.leak.check
      - TOKEN_CACHE_DURATION=3000

      # Rate Limiting
      - RATE_LIMIT_SINGLE_RPM=60
      - MAX_BATCH_SIZE=10000
    volumes:
      - leaklens_data:/app/data
    restart: unless-stopped
    networks:
      - leaklens-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  leaklens_data:
    driver: local

networks:
  leaklens-network:
    driver: bridge 