version: '3.8'

services:
  api:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    container_name: leaklens-api
    ports:
      - "10000:3000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - RUST_LOG=info
      - CORS_ALLOWED_ORIGINS=http://localhost:3001,http://webapp:3001
    restart: unless-stopped
    networks:
      - leaklens-network

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: leaklens-webapp
    depends_on:
      - api
    ports:
      - "8080:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3000
    restart: unless-stopped
    networks:
      - leaklens-network

networks:
  leaklens-network:
    driver: bridge
