services:
  # Combined service with API and WebApp
  - type: web
    name: leaklens
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: SERVER_PORT
        value: 3000
      - key: RUST_LOG
        value: info
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: "/api"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
    autoDeploy: true