services:
  # Backend API Service (Rust)
  - type: web
    name: leaklens-api
    env: docker
    rootDir: api_server
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: SERVER_PORT
        value: 3000
      - key: RUST_LOG
        value: info
      - key: CORS_ALLOWED_ORIGINS
        value: "*"  # Use wildcard for development; in production it will be replaced
    autoDeploy: true
  
  # Frontend Web App (Next.js)
  - type: web
    name: leaklens-webapp
    env: docker
    rootDir: webapp
    dockerfilePath: ./Dockerfile
    region: ohio
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: leaklens-api
          type: web
          property: url
    autoDeploy: true