# LeakLens API Server - Docker Compose Configuration
version: "3.8"

services:
  # API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaklens-api
    ports:
      - "3000:3000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
      - RUST_LOG=info
    volumes:
      - ./swagger.yaml:/app/swagger.yaml
      - ./.env.development:/app/.env
    restart: unless-stopped

  # Redis for caching and rate limiting (optional)
  redis:
    image: redis:7-alpine
    container_name: leaklens-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Development frontend
  frontend:
    image: node:18-alpine
    container_name: leaklens-frontend
    working_dir: /app
    volumes:
      - ../webapp:/app
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  redis-data: